-- Database Schema for Gym Tracker (PostgreSQL)

CREATE TABLE "User" (
  "id" SERIAL PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "email" VARCHAR(255) UNIQUE NOT NULL,
  "password" VARCHAR(255) NOT NULL,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Exercise" (
  "id" SERIAL PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "muscleGroup" VARCHAR(255) NOT NULL,
  "equipment" VARCHAR(255) NOT NULL,
  "userId" INTEGER NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Workout" (
  "id" SERIAL PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "date" TIMESTAMP NOT NULL,
  "userId" INTEGER NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "WorkoutExercise" (
  "id" SERIAL PRIMARY KEY,
  "workoutId" INTEGER NOT NULL REFERENCES "Workout"("id") ON DELETE CASCADE,
  "exerciseId" INTEGER NOT NULL REFERENCES "Exercise"("id") ON DELETE CASCADE
);

CREATE TABLE "WorkoutSet" (
  "id" SERIAL PRIMARY KEY,
  "workoutExerciseId" INTEGER NOT NULL REFERENCES "WorkoutExercise"("id") ON DELETE CASCADE,
  "weight" DOUBLE PRECISION NOT NULL,
  "reps" INTEGER NOT NULL,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
